# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://leonyen1995.github.io/
date_format: "ordinal"
title: Blog
subtitle: ""
description: "人是宇宙分之一"
keywords: Blog, Philosoophy, Art
favicon: /Mechanical.ico
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: Yan Haoqiang
organization: Imagine
organization_url: http://www.sjtu.edu.cn/
github_username: leonyen1995
location: Beijing, China
email: my email

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
mathjax: true
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji

repository: wuchuanxun/wuchuanxun.github.io

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
