# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://wuchuanxun.github.io/
date_format: "ordinal"
title: Blog
subtitle: "志同着，不以千里为远"
description: "吴传珣的个人博客"
keywords: BloG, Chuanxun Wu
favicon: /Mechanical.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: Chuanxun Wu
organization: SJTU
organization_url: http://www.sjtu.edu.cn/
github_username: wuchuanxun
location: Shanghai, China
email: wuchuanxun@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
mathjax: true
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji

repository: wuchuanxun/wuchuanxun.github.io

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
